import type { Scenario } from "./types";

export const SCENARIOS: Scenario[] = [
  {
    id: "url-shortener",
    name: "URL Shortener",
    prompt: "Design a URL shortener",
    kicker: "Hireable · redirects",
    brief:
      "TinyURL-class service: encode a long URL, 302 the hot codes, and never let analytics block the redirect.",
    load: "50k redirects/min peak · 10ms p99 on cache hits",
    constraint: "Redirect path cannot wait on a job, a session, or a lock.",
    track: "classic",
    nodes: [
      { id: "client", kind: "client", x: 16, y: 160 },
      { id: "cdn", kind: "cdn", x: 208, y: 160 },
      { id: "api", kind: "api", x: 400, y: 160 },
      { id: "rate-limit", kind: "rate-limit", x: 400, y: 28 },
      { id: "cache", kind: "cache", x: 608, y: 28 },
      { id: "database", kind: "database", x: 608, y: 160 },
      { id: "jobs", kind: "jobs", x: 608, y: 292 },
      { id: "auth", kind: "auth", x: 400, y: 292 },
    ],
    edges: [
      { from: "client", to: "cdn", flow: "read", sync: "sync" },
      { from: "cdn", to: "api", flow: "mixed", sync: "sync" },
      { from: "api", to: "rate-limit", flow: "mixed", sync: "sync" },
      { from: "api", to: "cache", flow: "read", sync: "sync" },
      { from: "api", to: "database", flow: "write", sync: "sync" },
      { from: "api", to: "auth", flow: "write", sync: "sync" },
      { from: "database", to: "jobs", flow: "write", sync: "async" },
    ],
  },
  {
    id: "social-feed",
    name: "Twitter Feed",
    prompt: "Design Twitter's home feed",
    kicker: "Hireable · fan-out",
    brief:
      "Follow-graph timeline. Ordinary posts fan out on write into per-user caches. Celebrity posts fall back to a hybrid read path. Search is a second store.",
    load: "2M DAU · write spikes at the hour",
    constraint: "The create-post HTTP request must not wait on follower fan-out.",
    track: "classic",
    nodes: [
      { id: "client", kind: "client", x: 16, y: 160 },
      { id: "api", kind: "api", x: 208, y: 160 },
      { id: "auth", kind: "auth", x: 208, y: 28 },
      { id: "authorization", kind: "authorization", x: 208, y: 292 },
      { id: "database", kind: "database", x: 416, y: 160 },
      { id: "cache", kind: "cache", x: 624, y: 28 },
      { id: "jobs", kind: "jobs", x: 624, y: 160 },
      { id: "search", kind: "search", x: 624, y: 292 },
    ],
    edges: [
      { from: "client", to: "api", flow: "mixed", sync: "sync" },
      { from: "api", to: "auth", flow: "mixed", sync: "sync" },
      { from: "api", to: "authorization", flow: "read", sync: "sync" },
      { from: "api", to: "database", flow: "write", sync: "sync" },
      { from: "database", to: "jobs", flow: "write", sync: "async" },
      { from: "jobs", to: "cache", flow: "write", sync: "async" },
      { from: "jobs", to: "search", flow: "write", sync: "async" },
      { from: "api", to: "cache", flow: "read", sync: "sync" },
    ],
  },
  {
    id: "realtime-chat",
    name: "WhatsApp",
    prompt: "Design WhatsApp",
    kicker: "Hireable · presence",
    brief:
      "1:1 and group delivery, presence, and history. HTTP persists; the socket layer fans out. Auth on the upgrade is part of the design.",
    load: "80k concurrent sockets · bursty send",
    constraint: "Do not store the room roster in a web worker's memory.",
    track: "classic",
    nodes: [
      { id: "client", kind: "client", x: 16, y: 160 },
      { id: "load-balancer", kind: "load-balancer", x: 208, y: 160 },
      { id: "api", kind: "api", x: 416, y: 28 },
      { id: "websocket", kind: "websocket", x: 416, y: 292 },
      { id: "auth", kind: "auth", x: 624, y: 28 },
      { id: "cache", kind: "cache", x: 624, y: 160 },
      { id: "database", kind: "database", x: 624, y: 292 },
      { id: "jobs", kind: "jobs", x: 416, y: 160 },
    ],
    edges: [
      { from: "client", to: "load-balancer", flow: "mixed", sync: "sync" },
      { from: "load-balancer", to: "api", flow: "mixed", sync: "sync" },
      { from: "load-balancer", to: "websocket", flow: "mixed", sync: "sync" },
      { from: "api", to: "auth", flow: "mixed", sync: "sync" },
      { from: "websocket", to: "auth", flow: "mixed", sync: "sync" },
      { from: "api", to: "jobs", flow: "write", sync: "async" },
      { from: "websocket", to: "cache", flow: "read", sync: "sync" },
      { from: "jobs", to: "database", flow: "write", sync: "async" },
      { from: "jobs", to: "cache", flow: "write", sync: "async" },
    ],
  },
  {
    id: "uber",
    name: "Uber",
    prompt: "Design Uber",
    kicker: "Hireable · dispatch",
    brief:
      "Riders request, drivers ping location, a matcher pairs them, trips persist. Location is hot and lossy; the trip record is not.",
    load: "Peak city · 1Hz driver pings",
    constraint: "Live location must not share a WAL with trip billing rows.",
    track: "classic",
    nodes: [
      { id: "client", kind: "client", x: 16, y: 160 },
      { id: "gateway", kind: "gateway", x: 208, y: 160 },
      { id: "api", kind: "api", x: 400, y: 160 },
      { id: "auth", kind: "auth", x: 208, y: 28 },
      { id: "cache", kind: "cache", x: 400, y: 28 },
      { id: "nosql", kind: "nosql", x: 608, y: 28 },
      { id: "database", kind: "database", x: 608, y: 160 },
      { id: "queue", kind: "queue", x: 400, y: 292 },
      { id: "jobs", kind: "jobs", x: 608, y: 292 },
    ],
    edges: [
      { from: "client", to: "gateway", flow: "mixed", sync: "sync" },
      { from: "gateway", to: "api", flow: "mixed", sync: "sync" },
      { from: "gateway", to: "auth", flow: "mixed", sync: "sync" },
      { from: "api", to: "cache", flow: "read", sync: "sync" },
      { from: "api", to: "nosql", flow: "write", sync: "sync" },
      { from: "api", to: "database", flow: "write", sync: "sync" },
      { from: "api", to: "queue", flow: "write", sync: "async" },
      { from: "queue", to: "jobs", flow: "write", sync: "async" },
    ],
  },
  {
    id: "rag-support",
    name: "RAG Support Agent",
    prompt: "Design an autonomous support agent with RAG",
    kicker: "AI Engineer · RAG",
    brief:
      "A ticket lands. The agent retrieves policy from a vector store, keeps session memory, calls an LLM through a gateway, and never burns the token budget on a loop.",
    load: "4k tickets/hour · grounded answers · citations required",
    constraint: "The model cannot see PII or the whole corpus. Retrieval is mandatory before generate.",
    track: "agentic",
    nodes: [
      { id: "client", kind: "client", x: 16, y: 160 },
      { id: "gateway", kind: "gateway", x: 208, y: 160 },
      { id: "api", kind: "api", x: 400, y: 160 },
      { id: "token-limiter", kind: "token-limiter", x: 208, y: 28 },
      { id: "llm-gateway", kind: "llm-gateway", x: 608, y: 28 },
      { id: "vector-db", kind: "vector-db", x: 608, y: 160 },
      { id: "agent-memory", kind: "agent-memory", x: 608, y: 292 },
      { id: "database", kind: "database", x: 400, y: 292 },
      { id: "cache", kind: "cache", x: 400, y: 28 },
    ],
    edges: [
      { from: "client", to: "gateway", flow: "mixed", sync: "sync" },
      { from: "gateway", to: "api", flow: "mixed", sync: "sync" },
      { from: "gateway", to: "token-limiter", flow: "mixed", sync: "sync" },
      { from: "api", to: "cache", flow: "read", sync: "sync" },
      { from: "api", to: "vector-db", flow: "read", sync: "sync" },
      { from: "api", to: "llm-gateway", flow: "write", sync: "sync" },
      { from: "api", to: "agent-memory", flow: "mixed", sync: "sync" },
      { from: "api", to: "database", flow: "write", sync: "sync" },
    ],
  },
  {
    id: "agentic-pipeline",
    name: "Agentic Pipeline",
    prompt: "Design an agentic execution pipeline with external tools",
    kicker: "AI Engineer · tools",
    brief:
      "A planner decomposes a task, a state machine checkpoints each hop, tools run in a sandbox, and a model router picks cheap vs. capable. Long-running work survives a crash.",
    load: "800 concurrent runs · multi-step tools · minutes-long jobs",
    constraint: "Tool I/O never executes in the API worker. State must resume after a killed process.",
    track: "agentic",
    nodes: [
      { id: "client", kind: "client", x: 16, y: 160 },
      { id: "api", kind: "api", x: 208, y: 160 },
      { id: "state-machine", kind: "state-machine", x: 400, y: 160 },
      { id: "token-limiter", kind: "token-limiter", x: 208, y: 28 },
      { id: "llm-gateway", kind: "llm-gateway", x: 608, y: 28 },
      { id: "sandbox", kind: "sandbox", x: 608, y: 160 },
      { id: "queue", kind: "queue", x: 400, y: 292 },
      { id: "agent-memory", kind: "agent-memory", x: 208, y: 292 },
      { id: "circuit-breaker", kind: "circuit-breaker", x: 608, y: 292 },
      { id: "database", kind: "database", x: 16, y: 292 },
    ],
    edges: [
      { from: "client", to: "api", flow: "mixed", sync: "sync" },
      { from: "api", to: "token-limiter", flow: "mixed", sync: "sync" },
      { from: "api", to: "state-machine", flow: "write", sync: "sync" },
      { from: "state-machine", to: "llm-gateway", flow: "write", sync: "sync" },
      { from: "state-machine", to: "sandbox", flow: "write", sync: "async" },
      { from: "state-machine", to: "queue", flow: "write", sync: "async" },
      { from: "state-machine", to: "agent-memory", flow: "mixed", sync: "sync" },
      { from: "sandbox", to: "circuit-breaker", flow: "write", sync: "sync" },
      { from: "state-machine", to: "database", flow: "write", sync: "async" },
    ],
  },
];

export function scenarioById(id: string): Scenario | undefined {
  return SCENARIOS.find((s) => s.id === id);
}

export const PALETTE_KINDS = [
  "cache",
  "replica",
  "queue",
  "rate-limit",
  "gateway",
  "nosql",
  "graph",
  "files",
  "circuit-breaker",
  "websocket",
  "cdn",
  "load-balancer",
  "jobs",
  "vector-db",
  "agent-memory",
  "llm-gateway",
  "sandbox",
  "token-limiter",
  "state-machine",
] as const;
