default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  port: <%= ENV.fetch("DB_PORT", "5432") %>
  username: <%= ENV.fetch("POSTGRES_USER", "lab") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "lab") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB", "lab") %>

test:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_TEST_DB", "lab_test") %>

production:
  primary:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
    database: <%= ENV.fetch("POSTGRES_DB", "lab") %>
    schema_search_path: <%= ENV.fetch("RAILS_SCHEMA", "public") %>
  queue:
    <<: *default
    url: <%= ENV["QUEUE_DATABASE_URL"] %>
    database: <%= ENV.fetch("POSTGRES_QUEUE_DB", "lab_queue") %>
    schema_search_path: <%= ENV.fetch("QUEUE_SCHEMA", "public") %>
    migrations_paths: db/queue_migrate
